theme: jekyll-theme-cayman

title: Haoxuan Xie's Homepage
description: Personal website of Haoxuan Xie
baseurl: "https://haoxuanxie.github.io"
url: "https://haoxuanxie.github.io" # the base hostname & protocol for your site

# Navigation links
navigation:
  - title: Home
    url: /home
  - title: Publications
    url: /publications
  - title: Blogs
    url: /blogs
  - title: CV
    url: /cv
