theme: jekyll-theme-cayman

title: Haoxuan Xie's Site
description: Welcome to my personal site

# Navigation links
navigation:
  - title: About
    url: /about
  - title: Publications
    url: /publications
  - title: Blogs
    url: /blogs
  - title: CV
    url: /cv
